MPFranquicia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('MusicPro.urls')),
    path("cuentas/", include("django.contrib.auth.urls")),
    path("cuentas/", include("loginApp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'MusicPro.views.error_404'

MusicPro/urls.py
from django.urls import path

from carritoApp.views import *
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('carrito/', views.carrito, name="carrito"),
    path('confirmar/', views.confirmarCompra, name="confirmar-compra"),
    path('realizada/', views.compraRealizada, name="compra-realizada"),
    path('pago/', views.realizar_pago, name="realizar-pago"),
    path('pago/realizado/', views.pago_realizado, name="pago-realizado"),
    path('pago/error/', views.pago_error, name="pago-error"),

    # Carrito
    path('agregar_carrito/<int:producto_id>', agregar_carrito, name='agregar_carrito'),
    path('eliminar_carrito/<int:producto_id>', eliminar_carrito, name='eliminar_carrito'),
    path('restar_carrito/<int:producto_id>', restar_carrito, name='restar_carrito'),
    path('limpiar_carrito/', limpiar_carrito, name='limpiar_carrito'),

    # Integraciones
    path('saludo/', views.saludo),
    path('saldo/', views.saldo),
    path('bodega/', views.bodega),
    path('enviarCorreo/', views.enviarCorreo, name='enviarCorreo'),
    path('transporte/', views.transporte, name='transporte'),
    path('seguimiento/', views.seguimiento, name='seguimiento'),

    #WebPay
    path('pago_webpay/', views.realizar_pago_webpay, name="realizar-pago-webpay"),
    path('pago/realizado_webpay/', views.pago_realizado_webpay, name="pago-realizado-webpay"),

    # CRUD
    path('gestionProductos/', views.gestionProductos, name='gestionProductos'),
    path('registrarProducto/' , views.registrarProducto, name='registrarProducto'),
    path('eliminarProducto/<int:id>/', views.eliminarProducto, name='eliminarProducto'),
    path('editarProducto/<int:id>/', views.editarProducto, name='editarProducto'),
]

MusicPro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Producto(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='productos', null=True)
    cantidad = models.IntegerField(default=0)
    tipo_instrumento = models.CharField(max_length=50, null=True)

    def __str__(self):
        texto = "{0} ({1})"
        return texto.format(self.nombre, self.cantidad)

class CodigoTransporte(models.Model):
    orden_compra = models.IntegerField(default=0)
    codigo_seguimiento = models.CharField(blank=True, max_length=70, verbose_name='Código de seguimiento', null=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    

class OrdenCompra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    productos = models.ManyToManyField('Producto', through='ItemOrdenCompra')
    direccion_envio = models.CharField(blank=True, max_length=70, verbose_name='Dirección del pedido', null=True)
    solicitud_exitosa = models.BooleanField(default=False, verbose_name='Solicitud exitosa')
    email = models.EmailField(default='example@example.com')
    
    class Meta:
        verbose_name_plural = "ordenes"

    def __str__(self):
        return f"Orden de compra #{self.id} - Usuario: {self.usuario.username} - Fecha: {self.fecha}"

class ItemOrdenCompra(models.Model):
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    orden_compra = models.ForeignKey('OrdenCompra', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = "items"

    def __str__(self):
        return f"Producto: {self.producto.nombre} - Cantidad: {self.cantidad}"
    
class DireccionEnvio(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "direcciones"

    def __str__(self):
        return self.direccion

MusicPro/forms.py
from django import forms
from .models import Producto,DireccionEnvio
from .validators import MaxSizeFileValidator
 

class ProductoForm(forms.ModelForm):

    nombre = forms.CharField(min_length=3, max_length=50)
    imagen = forms.ImageField(required=False, validators=[MaxSizeFileValidator(max_file_size=3)])
    precio = forms.IntegerField(min_value=1, max_value=1500000)
    tipo_instrumento = forms.CharField(min_length=3, max_length=50)


    class Meta:
        model = Producto
        fields = '__all__'

        #en caso de necesitar ingresar una fecha, se debe agregar el siguiente campo:
        #   widgets = {
        #       'fecha-fabricacion': forms.SelectDateWidget()
        #   }
        #fin de la fecha



class DireccionEnvioForm(forms.ModelForm):
    direccion = forms.CharField(max_length=100, label='Dirección')

    class Meta:
        model = DireccionEnvio
        fields = ["direccion"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        direccion_guardada = kwargs.get('instance')
        if direccion_guardada:
            self.initial['direccion'] = direccion_guardada.direccion

MusicPro/views.py
import random
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.db.models import Sum
from carritoApp.carrito import Carrito
from .models import Producto,ItemOrdenCompra, OrdenCompra,DireccionEnvio,CodigoTransporte
from .forms import ProductoForm,DireccionEnvioForm
from django.contrib import messages
import requests, json, datetime
from django.core.mail import send_mail
from django.conf import settings
import logging

#WebPay
from transbank.webpay.webpay_plus.transaction import Transaction, WebpayOptions, IntegrationApiKeys, IntegrationCommerceCodes
from transbank.common.integration_type import IntegrationType

#Vista Home
def home(request):
    productos = Producto.objects.all()
    return render(request, 'home.html', {'productos': productos})

#Vista integración Saludo
def saludo(request):
    response = requests.get('https://musicpro.bemtorres.win/api/v1/test/saludo')
    data = response.json()
    return render(request, 'apiSaludo.html', {"message": data['message']})

#Vista integración Saldo
def saldo(request):
    response = requests.get('https://musicpro.bemtorres.win/api/v1/test/saldo')
    data = response.json()
    return render(request, 'apiSaldo.html', {
        "message": data['message'],
        "saldo": data['saldo'],
        "saldo_raw": data['saldo_raw']
        })

#Vista integración Correo
def enviarCorreo(request):
    url = 'https://musicpro.bemtorres.win/api/v1/musicpro/send_email'
    try:
        response = requests.post(url, data={'asunto': 'hola', 'correo': 'ba.prado@duocuc.cl', 'contenido': ' esto es una prueba de mensaje'})
        data = response.json()
        print(data)
        
    except request.exceptions.RequestException as e:
        print(f'Error: {e}')

    return HttpResponse(data['message'])

#Vista integración Bodega
def bodega(request):
    response = requests.get('https://musicpro.bemtorres.win/api/v1/bodega/producto')
    data = response.json()
    return render(request, 'apiBodega.html', {
        "productos": data['productos'],
        })

#Vista Gestión Productos admin
def gestionProductos(request):
    if request.user.is_superuser:
        productos = Producto.objects.all()
        return render(request, 'gestionProductos.html', {'productos': productos})
    else:
        return render(request, '404.html')

#Vista agregar nuevo producto
def registrarProducto(request):
    print(request)
    data = {
        'form': ProductoForm()
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Producto agregado correctamente')
            return redirect('gestionProductos')
        else:
            messages.error(request, 'Error al agregar el producto')
            data['form'] = formulario
            return render(request, 'gestionProductos.html', data)

#Vista eliminar producto
def eliminarProducto(request, id):
    producto = Producto.objects.get(pk=id)
    producto.delete()
    messages.success(request, 'Producto eliminado correctamente')
    return redirect('gestionProductos')

#Vista Página404
def error_404(request, exception):
    return render(request, '404.html')

#Vista editar productos con modal
def editarProducto(request,id):
    if request.method == "POST":
        imagen = request.FILES.get('imagen')
        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        precio = request.POST.get('precio')
        cantidad = request.POST.get('cantidad')
        tipo_instrumento = request.POST.get('tipo_producto')

        producto = Producto(
            id = id,
            imagen = imagen,
            nombre = nombre,
            descripcion = descripcion,
            precio = precio,
            cantidad = cantidad,
            tipo_instrumento = tipo_instrumento
        )
        producto.save()
        messages.success(request, 'Producto editado correctamente')
        return redirect('gestionProductos')
    return redirect(request, 'home.html')

#Formulario transporte
'''def datosTransporte(request):
    data = {
        'form': TransporteForm()
    }
    if request.method == "POST":
        formulario = TransporteForm(data=request.POST)
        direccion_envio = request.POST.get('direccion_envio')
        metodo_pago = request.POST.get('metodo_pago')
        url = 'http://127.0.0.1:7000/api/v1/pedidos/'
        import random
        i = random.randint(1,9999)
        context = {
            'codigo': i, 
        }
        try:
            response = requests.post(url, data={'codigo_seguimiento': i, 
                                                'fecha_creacion': '', 
                                                'fecha_actualizacion': '',
                                                'estado': 'En preparacion',
                                                'direccion_envio': direccion_envio, 
                                                'metodo_pago': metodo_pago, 
                                                'usuario': 21, 
                                                'producto': [1]
                                                })
            data = response.json()
            print(data)  
        except request.exceptions.RequestException as e:
            print(f'Error: {e}')
        if formulario.is_valid():
            formulario.save()
            return render(request, 'envioDatosTransporte.html', context)
        else:
            data["form"] = formulario
    return render(request, 'datosTransporte.html', data)'''

'''def datosTransporte(request):
    data = {
        'form': TransporteForm()
    }
    if request.method == "POST":
        formulario = TransporteForm(data=request.POST)
        direccion_envio = request.POST.get('direccion_envio')
        url = 'https://musicpro.bemtorres.win/api/v1/transporte/solicitud'
        try:
            response = requests.post(url, data={'nombre_origen': request.user.username, 
                                                'direccion_origen': 'Av. Crimson 4245', 
                                                'nombre_destino': 'Patrick Star',
                                                'estado': 'En preparacion',
                                                'direccion_destino': direccion_envio, 
                                                'comentario': 'Primer intento', 
                                                'info': 'Carga con instrumentos pesados'
                                                })
            data = response.json()
            print(data)  
        except request.exceptions.RequestException as e:
            print(f'Error: {e}')
        if formulario.is_valid():
                formulario.save()
                # Vaciar el carrito después de realizar el pago
                carrito = Carrito(request)
                carrito.limpiar()
                return render(request, 'envioDatosTransporte.html', {'data': data})
        else:
            data["form"] = formulario
    return render(request, 'datosTransporte.html', data)'''

#Vista Carrito
def carrito(request):

    #Generar carrito
    carrito = Carrito(request)
    total = carrito.calcular_total()
    carrito_items = carrito.carrito.values()
    context = {
        'total': total,
        'carrito_items': carrito_items
    }
    return render(request, 'carrito.html', context)

#Vista Confirmar compra V2 (para actualizar o crear nuve direccion)
def confirmarCompra(request):
    # Generar carrito
    carrito = Carrito(request)
    total = carrito.calcular_total()
    print(total)
    carrito_items = carrito.carrito.values()
    direcciones = DireccionEnvio.objects.all()
    direccion_envio = DireccionEnvio.objects.filter(usuario=request.user).first()

    data = {
        'form': DireccionEnvioForm(),
        'total': total,
        'carrito_items': carrito_items,
        'direcciones': direcciones,
        'direccion_envio': direccion_envio.direccion if direccion_envio else None
    }

    if request.method == 'POST':
        formulario = DireccionEnvioForm(request.POST)
        if formulario.is_valid():
            direccion = formulario.cleaned_data['direccion']
            # Obtener la dirección existente del usuario (si la hay)
            direccion_envio = DireccionEnvio.objects.filter(usuario=request.user).first()
            if direccion_envio:
                # Actualizar la dirección existente
                direccion_envio.direccion = direccion
                direccion_envio.save()
                return redirect('confirmar-compra')
            else:
                # Crear una nueva dirección
                DireccionEnvio.objects.create(usuario=request.user, direccion=direccion)
                return redirect('confirmar-compra')
    else:
        formulario = DireccionEnvioForm()
        data['form'] = formulario

    return render(request, 'confirmarCompra.html', data)
    
    
#Vista Compra realizada
def compraRealizada(request):

    #Generar carrito
    carrito = Carrito(request)
    total = carrito.calcular_total()
    carrito_items = carrito.carrito.values()

    context = {
        'total': total,
        'carrito_items': carrito_items
    }
    
    direccion_envio = DireccionEnvio.objects.get(usuario=request.user)

    # Guardar la orden de compra
    if request.method == 'POST':
        usuario = request.user if request.user.is_authenticated else None
        if usuario:
            total_cantidad = 0
            orden_compra = OrdenCompra.objects.create(usuario=usuario,direccion_envio=direccion_envio.direccion,email=request.user.email)
            for item in carrito_items:
                producto = Producto.objects.get(id=item['producto_id'])
                ItemOrdenCompra.objects.create(
                        producto=producto,
                        orden_compra=orden_compra,

MusicPro/templates/apiSaldo.html
{% extends "baseHome.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <div class="col-12-md mb-5">
            <div class="card mb-3 mt-5">
                <div class="card-header">
                    Saldo
                </div>
                <div class="card-body">
                    <h5 class="card-title">Integración Api</h5>
                    <p class="card-text">{{message}}</p>
                    <p class="card-text">{{saldo}}</p>
                    <p class="card-text">{{saldo_raw}}</p>
                    <a href="../" class="btn btn-primary">Volver al Home</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

MusicPro/templates/apiSaludo.html
{% extends "baseHome.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <div class="col-12-md mb-5">
            <div class="card mb-3 mt-5">
                <div class="card-header">
                    Saludo
                </div>
                <div class="card-body">
                    <h5 class="card-title">Integración Api</h5>
                    <p class="card-text">{{message}}</p>
                    <a href="../" class="btn btn-primary">Volver al Home</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

MusicPro/templates/baseBarraNavegacion.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary" id="navbar">
    <div class="container-fluid d-flex justify-content-center" id="containerNav">
      <div class="row">
        <div class="col-md-4">
          <a href="../">
            <button class="btn btn">
              <img src="{% static 'img/bitmap.png' %}" height="70" alt="logoMusic" loading="lazy" />
            </button>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="col-md-8 mt-3">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="../" id="navbartext">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="../carrito/" id="navbartext">Carrito</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'seguimiento' %}" id="navbartext">Seguimiento</a>
              </li>
              {% if user.is_superuser %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false" id="navbartext">Administración</a>
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="../gestionProductos/"
                      id="productostext">Productos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'transporte' %}"
                      id="transporteText">Transporte</a>
                  </li>
                </ul>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <img src="{% static 'img/Icon/user.svg' %}" alt="userIcon">
                </a>
                <ul class="dropdown-menu text-center">
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="../../cuentas/logout_user">Cerrar Sesión</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="../../cuentas/login_user">Iniciar Sesión</a></li>
                  <li><a class="dropdown-item" href="../../cuentas/register_user">Registrarse</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
</body>

</html>

MusicPro/templates/baseHome.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <title>{% block title %} {% endblock %}</title>
    <link type='text/css' href='{% static "css\baseBarraNavegacion.css" %}' rel='stylesheet' />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css\baseBarraNavegacion.css' %}">
    <link rel="stylesheet" href="{% static 'css\navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css\styles.css' %}">
    <link rel="icon" href="{% static 'img/bitmap.png' %}" type="image/x-icon" id="iconPage">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
    {% include "baseBarraNavegacion.html" %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endfor %}
    {% endif %}


    <h1 id="titulo">Music Pro</h1>
    {% block content %}

    {% endblock %}

    <footer>
        <div class="container p-5 mt-5 text-center">
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                    <h5 class="mb-3">Links importantes</h5>
                    <ul class="list-unstyled mb-0">
                        <li class="mb-1">
                            <a href="#!">Home</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">Inicio Sesión</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">Carrito</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <h5 class="mb-3">Redes Sociales</h5>
                    <ul class="list-unstyled mb-0">
                        <li class="mb-1">
                            <a href="#!">Twitter</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">Instagram</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">Facebook</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <h5 class="mb-3">Contacto</h5>
                    <ul class="list-unstyled mb-0">
                        <li class="mb-1">
                            <a href="#!">Fono</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">Email</a>
                        </li>
                        <li class="mb-1">
                            <a href="#!">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="text-center p-3" id="copyright">
            © 2023 Copyright:
            <a class="text-dark" href="#">Music-Pro</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
    <script src="{% static 'js\gestionProductos.js' %}"></script>
    <script src="{% static 'js\modalTarjetas.js' %}"></script>
    <script src="https://kit.fontawesome.com/9db68f3690.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/dobleRequest.js' %}"></script>
    {% block scripts %}

    {% endblock %}
</body>

</html>

MusicPro/templates/compraRealizada.html
{% extends "baseHome.html" %}

{% load humanize %}

{% block title %}Compra realizada{% endblock %}

{% block content %}

<div class="container mt-3 mb-3">
    <div class="row justify-content-center">
        <div class="col-auto">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Orden de Compra</h4>
                </div>
                <div class="text-center mt-2">
                    <p class="fst-italic">Número de orden: {{ orden_compra.id }}</p>
                    <p class="fst-italic">Usuario: {{ orden_compra.usuario.username }}</p>
                    <p class="fst-italic">Fecha: {{ orden_compra.fecha }}</p>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead class="bg-light">
                            <tr>
                                <th scope="row">Nombre producto</th>
                                <th scope="row">Cantidad</th>
                                <th scope="row">Precio Unitario</th>
                                <th scope="row">Sub Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in carrito_items %}
                            <tr>
                                <td>
                                    <p class="fw-normal">{{ item.nombre }}</p>
                                </td>
                                <td>
                                    <p class="fw-normal">{{ item.cantidad }}</p>
                                </td>
                                <td>
                                    <p class="fw-normal">${{ item.precio | intcomma:False }}</p>
                                </td>
                                <td>
                                    <p class="fw-normal">${{ item.sub_total | intcomma:False }}</p>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot class="bg-light text-center">
                            <tr>
                                <td colspan="4">
                                    <p class="fw-normal"><strong>Total Compra:</strong> ${{ total | intcomma:False }}
                                    </p>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="card-footer text-center">
                    <a href="../"><button class="btn btn-success">Aceptar</button></a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

MusicPro/templates/transporte.html
{% extends "baseHome.html" %}

{% load static %}

{% block title %}Transporte{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12 text-center">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>Orden de compra</th>
                            <th>Cliente</th>
                            <th>Productos</th>
                            <th>Cantidad</th>
                            <th>Dirección</th>
                            <th>Transporte</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orden in ordenes %}
                        <tr>
                            <td>#{{ orden.id }}</td>
                            <td>{{ orden.usuario.username }}</td>
                            <td>
                                {% for item in orden.productos.all %}
                                {{ item.nombre }}
                                <br>
                                {% endfor %}
                            </td>
                            <td>
                                {% for item in orden.itemordencompra_set.all %}
                                {{ item.cantidad }}
                                <br>
                                {% endfor %}
                            </td>
                            <td>{{ orden.direccion_envio }}</td>
                            <td>
                                <form action="{% url 'transporte' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="orden_id" value="{{ orden.id }}">
                                    {% if orden.solicitud_exitosa %}
                                    <button type="button" class="btn btn-outline-success btn-sm" disabled>
                                        <i class="bi bi-check"></i> Solicitud enviada
                                    </button>
                                    {% else %}
                                    <select name="opcion" id="opcionesTransporte"
                                        class="form-select small-select center-select">
                                        <option value="MusicPro">Music Pro</option>
                                        <option value="GranJVCorp">GranJVCorp</option>
                                    </select>
                                    <br>
                                    <button type="submit" class="btn btn-warning btn-sm">
                                        <i class="bi bi-truck"></i> Solicitar transporte
                                    </button>
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}